--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/iZeaoGamer/InventoryCheck
branches:
- master
projects:
  InventoryCheck:
    libs:
    - src: muqsit/InvMenu/InvMenu
      version: ^2.1.0
      branch: master
      
   
...
